# Coding Temple's Data Analytics Program  
---
# Advanced Python - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [187]:
# Import numpy and assign it the standard alias
# YOUR CODE HERE
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [188]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [211]:
# Generate your random numbers
np.random.seed(68) #Seed generated for reproducibility

In [223]:
np.random.seed(68)
#YOUR CODE HERE
myarray = np.random.randint(0,100,(5,3))
# Print out the array
print(f'Here is a random array:\n {myarray}')

Here is a random array:
 [[63 39 36]
 [74 28 24]
 [23 84 79]
 [12 44 19]
 [47 19 27]]


### 1.2 Solution - Run the following cell to check your answer.

In [191]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [192]:
height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]

Arr_1 =np.array(height)
Arr_2= np.array(weight)

bmi= ((Arr_2*703)/(Arr_1**2))

print(bmi)

[39.50743802  8.7875     16.49012346 14.06      ]


### 1.3 Solution: Run the following cell to check your answer.

In [193]:
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'

### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [233]:
def my_func(rows,cols):
    return np.random.randint(0,1000,(rows,cols))

M = my_func(5,3)

print(M)

[[456 139 443]
 [181 833 649]
 [264 438 769]
 [602 596 907]
 [853  64 266]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [234]:
# 1. Return the first row:
print(M[0,:])

[456 139 443]


In [196]:
# 2. Return the last column
print(M[:,2])


[443 649 769 907 266]


In [197]:
# 3. Return the third column values from the 4th and 5th rows
print(M)
print('---------------------------')# was being annoyed with the poor visibility so I added these
print(M[3:5,2])

[[456 139 443]
 [181 833 649]
 [264 438 769]
 [602 596 907]
 [853  64 266]]
---------------------------
[907 266]


In [198]:
# 4. Multiply every value in the array by 2
M=M*2
print(M)

[[ 912  278  886]
 [ 362 1666 1298]
 [ 528  876 1538]
 [1204 1192 1814]
 [1706  128  532]]


In [199]:
# 5. Divide every value by 3
M= np.round(M/3,0)

print(M)

[[304.  93. 295.]
 [121. 555. 433.]
 [176. 292. 513.]
 [401. 397. 605.]
 [569.  43. 177.]]


In [200]:
# 6. Increase the values in the first row by 12
M[0,:] += 12

print(M[0,:])

[316. 105. 307.]


In [207]:
# 7. Calculate the mean of the first column
print(np.mean(M[0,:]))
#does this matter?
print(M[0,:].mean())

334.0
334.0


In [246]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
M = np.sort(M.reshape(1,15))
print(np.median(M[0,2:]))



596.0


In [249]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.seed(2) # New seed for new array
new_arry = np.random.randint(0,100,(5,3))
print(new_arry[0:3])
np.std(new_arry[0:3,])

[[40 15 72]
 [22 43 82]
 [75  7 34]]


25.81128091014125

In [261]:
# 10. Return values in the second column greater than 25
v=new_arry[:,1]
mask = np.where(v >25)
print(v[mask])

[43 95 47]


In [265]:
# 11. Return values < 40 in the array
print(new_arry[np.where(new_arry>40)])

[72 43 82 75 49 95 75 85 47 63]


### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [206]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])

The generated array: 
 [[31 90 20]
 [37 39 67]
 [ 4 42 51]
 [38 33 58]
 [67 69 88]]


1. The first row:  [31 90 20]


2. The last column:  [20 67 51 58 88]


3. The 3rd column, 4th & 5th rows:  [58 88]


4. Multiply by 2: 
 [[ 62 180  40]
 [ 74  78 134]
 [  8  84 102]
 [ 76  66 116]
 [134 138 176]]


5. Divide by 3: 
 [[10.33333333 30.          6.66666667]
 [12.33333333 13.         22.33333333]
 [ 1.33333333 14.         17.        ]
 [12.66666667 11.         19.33333333]
 [22.33333333 23.         29.33333333]]


6. Add 12 to the first row: 
 [ 43 102  32]


7. The mean of the 1st column:  35.4


8. The median after removing the 2 smallest values:  51.0


9. The standard deviation is:  18.755739862180263


10. All values in 2nd column > 25: 
 [[68 46 70]
 [95 83 31]
 [66 80 52]
 [76 50  4]
 [90 63 79]]


11. All values < 40: 
 [31  4]
